version: '3'

services:
  webserver:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynetwork


  database:
    image: mysql:8
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      mynetwork:
        aliases:
          - new_db
          - dev_db

networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/28

volumes:
  mysql_data:
    driver: local
